use tvos;
CREATE TABLE province(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `province_name` VARCHAR(255),
  `spot_num` TINYINT DEFAULT 0,
  `college_num` TINYINT DEFAULT 0,
  `creation_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `modification_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE city(
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `city_name` VARCHAR(255),
  `province_id` INT,
  `spot_num` INT DEFAULT 0,
  `creation_time` TIMESTAMP,
  `modification_time` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE city ADD FOREIGN KEY (`province_id`) REFERENCES province(`id`) ON DELETE CASCADE;
insert into province(province_name) values ('北京');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('上海');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('天津');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('重庆');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('香港');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('澳门');
set @lastid=(select last_insert_id());
insert into province(province_name) values ('河北');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('石家庄',(select @lastid));
insert into city(city_name,province_id) values('唐山',(select @lastid));
insert into city(city_name,province_id) values('邯郸',(select @lastid));
insert into city(city_name,province_id) values('秦皇岛',(select @lastid));
insert into city(city_name,province_id) values('保定',(select @lastid));
insert into city(city_name,province_id) values('张家口',(select @lastid));
insert into city(city_name,province_id) values('承德',(select @lastid));
insert into city(city_name,province_id) values('廊坊',(select @lastid));
insert into city(city_name,province_id) values('沧州',(select @lastid));
insert into city(city_name,province_id) values('衡水',(select @lastid));
insert into city(city_name,province_id) values('邢台',(select @lastid));
insert into province(province_name) values ('山西');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('太原',(select @lastid));
insert into city(city_name,province_id) values('大同',(select @lastid));
insert into city(city_name,province_id) values('阳泉',(select @lastid));
insert into city(city_name,province_id) values('长治',(select @lastid));
insert into city(city_name,province_id) values('晋城',(select @lastid));
insert into city(city_name,province_id) values('朔州',(select @lastid));
insert into city(city_name,province_id) values('忻州',(select @lastid));
insert into city(city_name,province_id) values('晋中',(select @lastid));
insert into city(city_name,province_id) values('临汾',(select @lastid));
insert into city(city_name,province_id) values('吕粱',(select @lastid));
insert into city(city_name,province_id) values('运城',(select @lastid));
insert into province(province_name) values ('辽宁');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('沈阳',(select @lastid));
insert into city(city_name,province_id) values('大连',(select @lastid));
insert into city(city_name,province_id) values('鞍山',(select @lastid));
insert into city(city_name,province_id) values('抚顺',(select @lastid));
insert into city(city_name,province_id) values('本溪',(select @lastid));
insert into city(city_name,province_id) values('丹东',(select @lastid));
insert into city(city_name,province_id) values('锦州 ',(select @lastid));
insert into city(city_name,province_id) values('葫芦岛',(select @lastid));
insert into city(city_name,province_id) values('营口',(select @lastid));
insert into city(city_name,province_id) values('盘锦',(select @lastid));
insert into city(city_name,province_id) values('阜新',(select @lastid));
insert into city(city_name,province_id) values('辽阳',(select @lastid));
insert into city(city_name,province_id) values('铁岭',(select @lastid));
insert into city(city_name,province_id) values('朝阳',(select @lastid));
insert into province(province_name) values ('吉林');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('长春',(select @lastid));
insert into city(city_name,province_id) values('吉林',(select @lastid));
insert into city(city_name,province_id) values('四平',(select @lastid));
insert into city(city_name,province_id) values('辽源',(select @lastid));
insert into city(city_name,province_id) values('通化',(select @lastid));
insert into city(city_name,province_id) values('白山',(select @lastid));
insert into city(city_name,province_id) values('松原',(select @lastid));
insert into city(city_name,province_id) values('白城',(select @lastid));
insert into city(city_name,province_id) values('延边自治州',(select @lastid));
insert into province(province_name) values ('黑龙江');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('哈尔滨',(select @lastid));
insert into city(city_name,province_id) values('齐齐哈尔',(select @lastid));
insert into city(city_name,province_id) values('鹤岗',(select @lastid));
insert into city(city_name,province_id) values('双鸭山',(select @lastid));
insert into city(city_name,province_id) values('鸡西',(select @lastid));
insert into city(city_name,province_id) values('大庆',(select @lastid));
insert into city(city_name,province_id) values('伊春',(select @lastid));
insert into city(city_name,province_id) values('牡丹江',(select @lastid));
insert into city(city_name,province_id) values('佳木斯',(select @lastid));
insert into city(city_name,province_id) values('七台河',(select @lastid));
insert into city(city_name,province_id) values('黑河',(select @lastid));
insert into city(city_name,province_id) values('绥化',(select @lastid));
insert into city(city_name,province_id) values('大兴安岭',(select @lastid));
insert into province(province_name) values ('江苏');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('南京',(select @lastid));
insert into city(city_name,province_id) values('无锡',(select @lastid));
insert into city(city_name,province_id) values('徐州',(select @lastid));
insert into city(city_name,province_id) values('常州',(select @lastid));
insert into city(city_name,province_id) values('苏州',(select @lastid));
insert into city(city_name,province_id) values('镇江',(select @lastid));
insert into city(city_name,province_id) values('南通',(select @lastid));
insert into city(city_name,province_id) values('扬州',(select @lastid));
insert into city(city_name,province_id) values('泰州',(select @lastid));
insert into city(city_name,province_id) values('盐城',(select @lastid));
insert into city(city_name,province_id) values('淮安',(select @lastid));
insert into city(city_name,province_id) values('连云港',(select @lastid));
insert into city(city_name,province_id) values('宿迁',(select @lastid));
insert into province(province_name) values ('浙江');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('杭州',(select @lastid));
insert into city(city_name,province_id) values('嘉兴',(select @lastid));
insert into city(city_name,province_id) values('湖州',(select @lastid));
insert into city(city_name,province_id) values('绍兴',(select @lastid));
insert into city(city_name,province_id) values('宁波',(select @lastid));
insert into city(city_name,province_id) values('台州',(select @lastid));
insert into city(city_name,province_id) values('温州',(select @lastid));
insert into city(city_name,province_id) values('金华',(select @lastid));
insert into city(city_name,province_id) values('衢州',(select @lastid));
insert into city(city_name,province_id) values('丽水',(select @lastid));
insert into city(city_name,province_id) values('舟山',(select @lastid));
insert into province(province_name) values ('安徽');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('合肥',(select @lastid));
insert into city(city_name,province_id) values('芜湖',(select @lastid));
insert into city(city_name,province_id) values('亳州',(select @lastid));
insert into city(city_name,province_id) values('淮北',(select @lastid));
insert into city(city_name,province_id) values('宿州',(select @lastid));
insert into city(city_name,province_id) values('阜阳',(select @lastid));
insert into city(city_name,province_id) values('蚌埠',(select @lastid));
insert into city(city_name,province_id) values('淮南',(select @lastid));
insert into city(city_name,province_id) values('滁州',(select @lastid));
insert into city(city_name,province_id) values('六安',(select @lastid));
insert into city(city_name,province_id) values('马鞍山',(select @lastid));
insert into city(city_name,province_id) values('安庆',(select @lastid));
insert into city(city_name,province_id) values('池州',(select @lastid));
insert into city(city_name,province_id) values('铜陵',(select @lastid));
insert into city(city_name,province_id) values('宣城',(select @lastid));
insert into city(city_name,province_id) values('黄山',(select @lastid));
insert into province(province_name) values ('福建');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('福州',(select @lastid));
insert into city(city_name,province_id) values('厦门',(select @lastid));
insert into city(city_name,province_id) values('泉州',(select @lastid));
insert into city(city_name,province_id) values('莆田',(select @lastid));
insert into city(city_name,province_id) values('三明',(select @lastid));
insert into city(city_name,province_id) values('漳州',(select @lastid));
insert into city(city_name,province_id) values('南平',(select @lastid));
insert into city(city_name,province_id) values('龙岩',(select @lastid));
insert into city(city_name,province_id) values('宁德',(select @lastid));
insert into province(province_name) values ('江西');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('南昌',(select @lastid));
insert into city(city_name,province_id) values('九江',(select @lastid));
insert into city(city_name,province_id) values('景德镇',(select @lastid));
insert into city(city_name,province_id) values('萍乡',(select @lastid));
insert into city(city_name,province_id) values('新余',(select @lastid));
insert into city(city_name,province_id) values('鹰潭',(select @lastid));
insert into city(city_name,province_id) values('赣州',(select @lastid));
insert into city(city_name,province_id) values('宜春',(select @lastid));
insert into city(city_name,province_id) values('上饶',(select @lastid));
insert into city(city_name,province_id) values('吉安',(select @lastid));
insert into city(city_name,province_id) values('抚州',(select @lastid));
insert into province(province_name) values ('山东');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('济南',(select @lastid));
insert into city(city_name,province_id) values('菏泽',(select @lastid));
insert into city(city_name,province_id) values('青岛',(select @lastid));
insert into city(city_name,province_id) values('淄博',(select @lastid));
insert into city(city_name,province_id) values('枣庄',(select @lastid));
insert into city(city_name,province_id) values('东营',(select @lastid));
insert into city(city_name,province_id) values('烟台',(select @lastid));
insert into city(city_name,province_id) values('潍坊',(select @lastid));
insert into city(city_name,province_id) values('济宁',(select @lastid));
insert into city(city_name,province_id) values('泰安',(select @lastid));
insert into city(city_name,province_id) values('威海',(select @lastid));
insert into city(city_name,province_id) values('日照',(select @lastid));
insert into city(city_name,province_id) values('滨州',(select @lastid));
insert into city(city_name,province_id) values('德州',(select @lastid));
insert into city(city_name,province_id) values('聊城',(select @lastid));
insert into city(city_name,province_id) values('临沂',(select @lastid));
insert into city(city_name,province_id) values('莱芜',(select @lastid));
insert into province(province_name) values ('河南');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('郑州',(select @lastid));
insert into city(city_name,province_id) values('洛阳',(select @lastid));
insert into city(city_name,province_id) values('商丘',(select @lastid));
insert into city(city_name,province_id) values('安阳',(select @lastid));
insert into city(city_name,province_id) values('南阳',(select @lastid));
insert into city(city_name,province_id) values('开封',(select @lastid));
insert into city(city_name,province_id) values('平顶山',(select @lastid));
insert into city(city_name,province_id) values('焦作',(select @lastid));
insert into city(city_name,province_id) values('新乡',(select @lastid));
insert into city(city_name,province_id) values('鹤壁',(select @lastid));
insert into city(city_name,province_id) values('濮阳',(select @lastid));
insert into city(city_name,province_id) values('许昌',(select @lastid));
insert into city(city_name,province_id) values('漯河',(select @lastid));
insert into city(city_name,province_id) values('三门峡',(select @lastid));
insert into city(city_name,province_id) values('信阳',(select @lastid));
insert into city(city_name,province_id) values('周口',(select @lastid));
insert into city(city_name,province_id) values('驻马店',(select @lastid));
insert into city(city_name,province_id) values('济源',(select @lastid));
insert into province(province_name) values ('湖北');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('武汉',(select @lastid));
insert into city(city_name,province_id) values('宜昌',(select @lastid));
insert into city(city_name,province_id) values('黄石',(select @lastid));
insert into city(city_name,province_id) values('十堰',(select @lastid));
insert into city(city_name,province_id) values('荆州',(select @lastid));
insert into city(city_name,province_id) values('襄樊',(select @lastid));
insert into city(city_name,province_id) values('鄂州',(select @lastid));
insert into city(city_name,province_id) values('荆门',(select @lastid));
insert into city(city_name,province_id) values('孝感',(select @lastid));
insert into city(city_name,province_id) values('黄冈',(select @lastid));
insert into city(city_name,province_id) values('咸宁',(select @lastid));
insert into city(city_name,province_id) values('随州',(select @lastid));
insert into city(city_name,province_id) values('仙桃',(select @lastid));
insert into city(city_name,province_id) values('天门',(select @lastid));
insert into city(city_name,province_id) values('潜江',(select @lastid));
insert into city(city_name,province_id) values('恩施自治州',(select @lastid));
insert into city(city_name,province_id) values('神农架林区',(select @lastid));
insert into province(province_name) values ('湖南');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('长沙',(select @lastid));
insert into city(city_name,province_id) values('株洲',(select @lastid));
insert into city(city_name,province_id) values('湘潭',(select @lastid));
insert into city(city_name,province_id) values('衡阳',(select @lastid));
insert into city(city_name,province_id) values('邵阳',(select @lastid));
insert into city(city_name,province_id) values('岳阳',(select @lastid));
insert into city(city_name,province_id) values('常德',(select @lastid));
insert into city(city_name,province_id) values('张家界',(select @lastid));
insert into city(city_name,province_id) values('益阳',(select @lastid));
insert into city(city_name,province_id) values('郴州',(select @lastid));
insert into city(city_name,province_id) values('永州',(select @lastid));
insert into city(city_name,province_id) values('怀化',(select @lastid));
insert into city(city_name,province_id) values('娄底',(select @lastid));
insert into city(city_name,province_id) values('湘西自治州',(select @lastid));
insert into province(province_name) values ('广东');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('广州',(select @lastid));
insert into city(city_name,province_id) values('深圳',(select @lastid));
insert into city(city_name,province_id) values('珠海',(select @lastid));
insert into city(city_name,province_id) values('佛山',(select @lastid));
insert into city(city_name,province_id) values('东莞',(select @lastid));
insert into city(city_name,province_id) values('中山',(select @lastid));
insert into city(city_name,province_id) values('汕头',(select @lastid));
insert into city(city_name,province_id) values('韶关',(select @lastid));
insert into city(city_name,province_id) values('江门',(select @lastid));
insert into city(city_name,province_id) values('茂名',(select @lastid));
insert into city(city_name,province_id) values('湛江',(select @lastid));
insert into city(city_name,province_id) values('肇庆',(select @lastid));
insert into city(city_name,province_id) values('梅州',(select @lastid));
insert into city(city_name,province_id) values('汕尾',(select @lastid));
insert into city(city_name,province_id) values('河源',(select @lastid));
insert into city(city_name,province_id) values('阳江',(select @lastid));
insert into city(city_name,province_id) values('清远',(select @lastid));
insert into city(city_name,province_id) values('潮州',(select @lastid));
insert into city(city_name,province_id) values('揭阳',(select @lastid));
insert into city(city_name,province_id) values('云浮',(select @lastid));
insert into city(city_name,province_id) values('惠州',(select @lastid));
insert into city(city_name,province_id) values('东沙群岛',(select @lastid));
insert into province(province_name) values ('海南');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('海口',(select @lastid));
insert into city(city_name,province_id) values('三亚',(select @lastid));
insert into city(city_name,province_id) values('三沙',(select @lastid));
insert into city(city_name,province_id) values('五指山',(select @lastid));
insert into city(city_name,province_id) values('琼海',(select @lastid));
insert into city(city_name,province_id) values('儋州',(select @lastid));
insert into city(city_name,province_id) values('文昌',(select @lastid));
insert into city(city_name,province_id) values('万宁',(select @lastid));
insert into city(city_name,province_id) values('东方',(select @lastid));
insert into city(city_name,province_id) values('澄迈县',(select @lastid));
insert into city(city_name,province_id) values('定安县',(select @lastid));
insert into city(city_name,province_id) values('屯昌县',(select @lastid));
insert into city(city_name,province_id) values('临高县',(select @lastid));
insert into city(city_name,province_id) values('白沙自治县',(select @lastid));
insert into city(city_name,province_id) values('昌江自治县',(select @lastid));
insert into city(city_name,province_id) values('乐东自治县',(select @lastid));
insert into city(city_name,province_id) values('陵水自治县',(select @lastid));
insert into city(city_name,province_id) values('▪保亭自治县',(select @lastid));
insert into city(city_name,province_id) values('琼中自治县',(select @lastid));
insert into province(province_name) values ('四川');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('成都',(select @lastid));
insert into city(city_name,province_id) values('自贡',(select @lastid));
insert into city(city_name,province_id) values('攀枝花',(select @lastid));
insert into city(city_name,province_id) values('泸州',(select @lastid));
insert into city(city_name,province_id) values('德阳',(select @lastid));
insert into city(city_name,province_id) values('绵阳',(select @lastid));
insert into city(city_name,province_id) values('广元',(select @lastid));
insert into city(city_name,province_id) values('遂宁',(select @lastid));
insert into city(city_name,province_id) values('内江',(select @lastid));
insert into city(city_name,province_id) values('乐山',(select @lastid));
insert into city(city_name,province_id) values('南充',(select @lastid));
insert into city(city_name,province_id) values('宜宾',(select @lastid));
insert into city(city_name,province_id) values('广安',(select @lastid));
insert into city(city_name,province_id) values('达州',(select @lastid));
insert into city(city_name,province_id) values('眉山',(select @lastid));
insert into city(city_name,province_id) values('雅安',(select @lastid));
insert into city(city_name,province_id) values('巴中',(select @lastid));
insert into city(city_name,province_id) values('资阳',(select @lastid));
insert into city(city_name,province_id) values('阿坝自治州',(select @lastid));
insert into city(city_name,province_id) values('甘孜自治州',(select @lastid));
insert into city(city_name,province_id) values('凉山自治州',(select @lastid));
insert into province(province_name) values ('贵州');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('贵阳',(select @lastid));
insert into city(city_name,province_id) values('六盘水',(select @lastid));
insert into city(city_name,province_id) values('遵义',(select @lastid));
insert into city(city_name,province_id) values('安顺',(select @lastid));
insert into city(city_name,province_id) values('毕节',(select @lastid));
insert into city(city_name,province_id) values('铜仁',(select @lastid));
insert into city(city_name,province_id) values('黔西南自治州',(select @lastid));
insert into city(city_name,province_id) values('黔东南自治州',(select @lastid));
insert into city(city_name,province_id) values('黔南自治州',(select @lastid));
insert into province(province_name) values ('云南');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('昆明',(select @lastid));
insert into city(city_name,province_id) values('曲靖',(select @lastid));
insert into city(city_name,province_id) values('玉溪',(select @lastid));
insert into city(city_name,province_id) values('保山',(select @lastid));
insert into city(city_name,province_id) values('昭通',(select @lastid));
insert into city(city_name,province_id) values('丽江',(select @lastid));
insert into city(city_name,province_id) values('普洱',(select @lastid));
insert into city(city_name,province_id) values('临沧',(select @lastid));
insert into city(city_name,province_id) values('文山自治州',(select @lastid));
insert into city(city_name,province_id) values('红河自治州',(select @lastid));
insert into city(city_name,province_id) values('西双版纳自治州',(select @lastid));
insert into city(city_name,province_id) values('楚雄自治州',(select @lastid));
insert into city(city_name,province_id) values('大理自治州',(select @lastid));
insert into city(city_name,province_id) values('德宏自治州',(select @lastid));
insert into city(city_name,province_id) values('怒江自治州',(select @lastid));
insert into city(city_name,province_id) values('迪庆自治州',(select @lastid));
insert into province(province_name) values ('陕西');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('西安',(select @lastid));
insert into city(city_name,province_id) values('铜川',(select @lastid));
insert into city(city_name,province_id) values('宝鸡',(select @lastid));
insert into city(city_name,province_id) values('咸阳',(select @lastid));
insert into city(city_name,province_id) values('渭南',(select @lastid));
insert into city(city_name,province_id) values('延安',(select @lastid));
insert into city(city_name,province_id) values('汉中',(select @lastid));
insert into city(city_name,province_id) values('榆林',(select @lastid));
insert into city(city_name,province_id) values('安康',(select @lastid));
insert into city(city_name,province_id) values('商洛',(select @lastid));
insert into province(province_name) values ('甘肃');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('兰州',(select @lastid));
insert into city(city_name,province_id) values('庆阳',(select @lastid));
insert into city(city_name,province_id) values('天水',(select @lastid));
insert into city(city_name,province_id) values('酒泉',(select @lastid));
insert into city(city_name,province_id) values('武威',(select @lastid));
insert into city(city_name,province_id) values('白银',(select @lastid));
insert into city(city_name,province_id) values('张掖',(select @lastid));
insert into city(city_name,province_id) values('平凉',(select @lastid));
insert into city(city_name,province_id) values('陇南',(select @lastid));
insert into city(city_name,province_id) values('定西',(select @lastid));
insert into city(city_name,province_id) values('金昌',(select @lastid));
insert into city(city_name,province_id) values('嘉峪关',(select @lastid));
insert into city(city_name,province_id) values('临夏自治州',(select @lastid));
insert into city(city_name,province_id) values('甘南自治州',(select @lastid));
insert into province(province_name) values ('青海');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('西宁',(select @lastid));
insert into city(city_name,province_id) values('海东',(select @lastid));
insert into city(city_name,province_id) values('海北自治区',(select @lastid));
insert into city(city_name,province_id) values('海南自治区',(select @lastid));
insert into city(city_name,province_id) values('黄南自治区',(select @lastid));
insert into city(city_name,province_id) values('果洛自治区',(select @lastid));
insert into city(city_name,province_id) values('玉树自治区',(select @lastid));
insert into city(city_name,province_id) values('海西自治区',(select @lastid));
insert into province(province_name) values ('台湾');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('台北',(select @lastid));
insert into city(city_name,province_id) values('新北',(select @lastid));
insert into city(city_name,province_id) values('桃园',(select @lastid));
insert into city(city_name,province_id) values('台中',(select @lastid));
insert into city(city_name,province_id) values('台南',(select @lastid));
insert into city(city_name,province_id) values('高雄',(select @lastid));
insert into city(city_name,province_id) values('基隆',(select @lastid));
insert into city(city_name,province_id) values(' 新竹',(select @lastid));
insert into city(city_name,province_id) values(' 嘉义',(select @lastid));
insert into province(province_name) values ('内蒙古');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('呼和浩特',(select @lastid));
insert into city(city_name,province_id) values('包头',(select @lastid));
insert into city(city_name,province_id) values('乌海',(select @lastid));
insert into city(city_name,province_id) values('赤峰',(select @lastid));
insert into city(city_name,province_id) values('通辽',(select @lastid));
insert into city(city_name,province_id) values('鄂尔多斯',(select @lastid));
insert into city(city_name,province_id) values('呼伦贝尔',(select @lastid));
insert into city(city_name,province_id) values('巴彦淖尔',(select @lastid));
insert into city(city_name,province_id) values('乌兰察布',(select @lastid));
insert into city(city_name,province_id) values('兴安盟',(select @lastid));
insert into city(city_name,province_id) values('锡林郭勒盟',(select @lastid));
insert into city(city_name,province_id) values('阿拉善盟',(select @lastid));
insert into province(province_name) values ('广西');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('南宁',(select @lastid));
insert into city(city_name,province_id) values('柳州',(select @lastid));
insert into city(city_name,province_id) values('桂林',(select @lastid));
insert into city(city_name,province_id) values('梧州',(select @lastid));
insert into city(city_name,province_id) values('北海',(select @lastid));
insert into city(city_name,province_id) values('防城港',(select @lastid));
insert into city(city_name,province_id) values('钦州',(select @lastid));
insert into city(city_name,province_id) values('贵港',(select @lastid));
insert into city(city_name,province_id) values('玉林',(select @lastid));
insert into city(city_name,province_id) values('百色',(select @lastid));
insert into city(city_name,province_id) values('贺州',(select @lastid));
insert into city(city_name,province_id) values('河池',(select @lastid));
insert into city(city_name,province_id) values('来宾',(select @lastid));
insert into city(city_name,province_id) values('崇左',(select @lastid));
insert into province(province_name) values ('西藏');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('拉萨',(select @lastid));
insert into city(city_name,province_id) values('日喀则',(select @lastid));
insert into city(city_name,province_id) values('昌都',(select @lastid));
insert into city(city_name,province_id) values('林芝',(select @lastid));
insert into city(city_name,province_id) values('山南',(select @lastid));
insert into city(city_name,province_id) values('那曲地区',(select @lastid));
insert into city(city_name,province_id) values('阿里地区',(select @lastid));
insert into province(province_name) values ('宁夏');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('银川',(select @lastid));
insert into city(city_name,province_id) values('石嘴山',(select @lastid));
insert into city(city_name,province_id) values('吴忠',(select @lastid));
insert into city(city_name,province_id) values('固原',(select @lastid));
insert into city(city_name,province_id) values('中卫',(select @lastid));
insert into province(province_name) values ('新疆');
set @lastid=(select last_insert_id());
insert into city(city_name,province_id) values('乌鲁木齐',(select @lastid));
insert into city(city_name,province_id) values('克拉玛依',(select @lastid));
insert into city(city_name,province_id) values('吐鲁番',(select @lastid));
insert into city(city_name,province_id) values('哈密',(select @lastid));
insert into city(city_name,province_id) values('石河子',(select @lastid));
insert into city(city_name,province_id) values('阿拉尔',(select @lastid));
insert into city(city_name,province_id) values('图木舒克',(select @lastid));
insert into city(city_name,province_id) values('五家渠',(select @lastid));
insert into city(city_name,province_id) values('北屯',(select @lastid));
insert into city(city_name,province_id) values('铁门关',(select @lastid));
insert into city(city_name,province_id) values('双河',(select @lastid));
insert into city(city_name,province_id) values('可克达拉',(select @lastid));
insert into city(city_name,province_id) values('昆玉',(select @lastid));
insert into city(city_name,province_id) values('昌吉州',(select @lastid));
insert into city(city_name,province_id) values('博尔塔拉州',(select @lastid));
insert into city(city_name,province_id) values('巴音郭楞州',(select @lastid));
insert into city(city_name,province_id) values('克孜勒苏州',(select @lastid));
insert into city(city_name,province_id) values('伊犁州',(select @lastid));
insert into city(city_name,province_id) values('阿克苏地区',(select @lastid));
insert into city(city_name,province_id) values('喀什地区',(select @lastid));
insert into city(city_name,province_id) values('和田地区',(select @lastid));
insert into city(city_name,province_id) values('塔城地区',(select @lastid));
insert into city(city_name,province_id) values('阿勒泰地区',(select @lastid));
